import { StyleSheet } from 'react-native';
import { ThemeColors, Typography, BorderRadius, Spacing } from '../../constants/theme';

export const createTasksStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: Spacing.md,
      marginBottom: Spacing.xs,
    },
    headerTitle: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xxl,
      fontWeight: Typography.fontWeight.heavy,
      color: colors.text,
      letterSpacing: -0.4,
    },
    headerSubtitle: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xs,
      color: colors.textMuted,
      marginTop: 2,
    },
    searchContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.glassCard,
      borderWidth: 1,
      borderColor: colors.glassBorder,
      borderTopColor: colors.glassSpecular,
      borderRadius: BorderRadius.xl,
      paddingHorizontal: Spacing.md,
      height: 50,
      marginBottom: Spacing.md,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 3,
    },
    searchIcon: {
      marginRight: Spacing.sm,
    },
    searchInput: {
      flex: 1,
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.md,
      color: colors.text,
    },
    filterScroll: {
      marginBottom: 10,
      maxHeight: 44,
    },
    filterContent: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 2,
    },
    filterChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: Spacing.md,
      paddingVertical: 8,
      borderRadius: BorderRadius.full,
      backgroundColor: colors.glassCard,
      borderWidth: 1,
      borderColor: colors.glassBorder,
      borderTopColor: colors.glassSpecular,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    filterChipActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primaryLight,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.4,
      shadowRadius: 10,
      elevation: 5,
    },
    filterText: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xs,
      fontWeight: Typography.fontWeight.semibold,
      color: colors.textSecondary,
    },
    filterTextActive: {
      color: '#FFFFFF',
      fontWeight: Typography.fontWeight.bold,
    },
    filterBadge: {
      backgroundColor: 'rgba(255, 255, 255, 0.18)',
      borderRadius: 10,
      paddingHorizontal: 6,
      paddingVertical: 1,
    },
    filterBadgeText: {
      fontFamily: Typography.fontFamily,
      fontSize: 10,
      fontWeight: '800',
      color: '#FFFFFF',
    },
    listContent: {
      paddingBottom: 100,
      paddingTop: 4,
    },
    emptyContainer: {
      backgroundColor: colors.glassCard,
      borderRadius: BorderRadius.xl,
      padding: Spacing.xxxl,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.glassBorder,
      borderTopColor: colors.glassSpecular,
      marginTop: Spacing.xl,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.2,
      shadowRadius: 12,
      elevation: 4,
    },
    emptyIcon: {
      marginBottom: Spacing.md,
    },
    emptyTitle: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.lg,
      fontWeight: Typography.fontWeight.bold,
      color: colors.text,
      textAlign: 'center',
    },
    emptySub: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.sm,
      color: colors.textMuted,
      marginTop: 4,
      textAlign: 'center',
    },
  });
