import { StyleSheet } from 'react-native';
import { ThemeColors, Typography, BorderRadius, Spacing } from '../../constants/theme';

export const createDashboardStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    scrollContent: {
      paddingBottom: Spacing.xxxl,
    },
    topHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: Spacing.md,
      marginBottom: Spacing.xs,
    },
    greetingContainer: {
      flex: 1,
      marginRight: Spacing.md,
    },
    greetingRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    greetingText: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xxl,
      fontWeight: Typography.fontWeight.heavy,
      color: colors.text,
      letterSpacing: -0.5,
    },
    greetingIcon: {
      marginLeft: 6,
    },
    workspaceIdBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      marginTop: 4,
    },
    workspaceIdText: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xs,
      color: colors.primaryLight,
      fontWeight: Typography.fontWeight.semibold,
      letterSpacing: 0.2,
    },
    headerRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    glassIconBtn: {
      width: 44,
      height: 44,
      borderRadius: BorderRadius.lg,
      backgroundColor: colors.glassCard,
      borderWidth: 1,
      borderColor: colors.glassBorder,
      borderTopColor: colors.glassSpecular,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 4,
    },
    notifBadge: {
      position: 'absolute',
      top: -3,
      right: -3,
      backgroundColor: colors.accentPink,
      borderRadius: 10,
      minWidth: 18,
      height: 18,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 4,
      borderWidth: 2,
      borderColor: colors.background,
    },
    notifBadgeText: {
      fontFamily: Typography.fontFamily,
      color: '#FFFFFF',
      fontSize: 10,
      fontWeight: '800',
    },
    avatarCircle: {
      width: 44,
      height: 44,
      borderRadius: BorderRadius.lg,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: colors.glassBorderHighlight,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.35,
      shadowRadius: 10,
      elevation: 6,
      overflow: 'hidden',
    },
    avatarImage: {
      width: '100%',
      height: '100%',
      borderRadius: BorderRadius.lg,
    },
    avatarText: {
      fontFamily: Typography.fontFamily,
      color: '#FFFFFF',
      fontSize: Typography.fontSize.lg,
      fontWeight: Typography.fontWeight.bold,
    },

    // 2x2 Summary Metric Cards Grid
    summaryGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      gap: 12,
      marginTop: Spacing.sm,
      marginBottom: Spacing.md,
    },

    // Quick Actions Bar
    quickActionsSection: {
      marginBottom: Spacing.lg,
    },
    quickActionsScroll: {
      paddingVertical: 4,
    },
    quickActionChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: BorderRadius.xl,
      backgroundColor: colors.glassCard,
      borderWidth: 1,
      borderColor: colors.glassBorder,
      borderTopColor: colors.glassSpecular,
      marginRight: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 6,
      elevation: 3,
    },
    quickActionIconBox: {
      width: 26,
      height: 26,
      borderRadius: 13,
      alignItems: 'center',
      justifyContent: 'center',
    },
    quickActionText: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xs,
      fontWeight: Typography.fontWeight.bold,
      color: colors.text,
    },

    // Liquid Glass Daily Progress Card
    glassCard: {
      backgroundColor: colors.glassCard,
      borderRadius: BorderRadius.xl,
      padding: Spacing.lg,
      borderWidth: 1,
      borderColor: colors.glassBorder,
      borderTopColor: colors.glassSpecular,
      marginBottom: Spacing.lg,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.2,
      shadowRadius: 16,
      elevation: 6,
    },
    progressHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: Spacing.sm,
    },
    progressTitle: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.md,
      fontWeight: Typography.fontWeight.bold,
      color: colors.text,
    },
    progressPercentageTag: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: BorderRadius.full,
      backgroundColor: `${colors.primary}25`,
      borderWidth: 1,
      borderColor: `${colors.primary}40`,
    },
    progressPercentageText: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xs,
      fontWeight: Typography.fontWeight.heavy,
      color: colors.primaryLight,
    },
    progressSubtext: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xs,
      color: colors.textMuted,
      marginBottom: Spacing.sm,
    },
    progressBarBg: {
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.surfaceHighlight,
      overflow: 'hidden',
    },
    progressBarFill: {
      height: '100%',
      borderRadius: 4,
      backgroundColor: colors.primary,
    },

    // Empty Schedule State
    emptySchedule: {
      backgroundColor: colors.glassCard,
      borderRadius: BorderRadius.xl,
      padding: Spacing.xl,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.glassBorder,
      borderTopColor: colors.glassSpecular,
      marginBottom: Spacing.md,
    },
    emptyScheduleIcon: {
      marginBottom: Spacing.sm,
    },
    emptyScheduleText: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.md,
      color: colors.text,
      fontWeight: Typography.fontWeight.semibold,
      textAlign: 'center',
    },
    emptyScheduleSub: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xs,
      color: colors.textMuted,
      marginTop: 4,
      textAlign: 'center',
    },
    emptyScheduleBtn: {
      marginTop: Spacing.md,
      paddingHorizontal: Spacing.lg,
      paddingVertical: Spacing.sm,
      borderRadius: BorderRadius.lg,
      backgroundColor: colors.surfaceHighlight,
      borderWidth: 1,
      borderColor: colors.glassBorder,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    emptyScheduleBtnText: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xs,
      fontWeight: Typography.fontWeight.bold,
      color: colors.primaryLight,
    },
  });
