import { StyleSheet } from 'react-native';
import { ThemeColors, Typography, BorderRadius, Spacing } from '../../constants/theme';

export const createDashboardStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    scrollContent: {
      paddingBottom: Spacing.xxxl,
    },
    topHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: Spacing.md,
      marginBottom: Spacing.xs,
    },
    greetingContainer: {
      flex: 1,
    },
    greetingRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    greetingText: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xxl,
      fontWeight: Typography.fontWeight.heavy,
      color: colors.text,
      letterSpacing: -0.4,
    },
    greetingIcon: {
      marginLeft: 6,
    },
    workspaceIdBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 4,
    },
    workspaceIdText: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xs,
      color: colors.primaryLight,
      fontWeight: Typography.fontWeight.semibold,
      letterSpacing: 0.2,
    },
    headerRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    glassIconBtn: {
      width: 44,
      height: 44,
      borderRadius: BorderRadius.md,
      backgroundColor: colors.glassCard,
      borderWidth: 1,
      borderColor: colors.glassBorder,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 4,
    },
    notifBadge: {
      position: 'absolute',
      top: -3,
      right: -3,
      backgroundColor: colors.accentPink,
      borderRadius: 10,
      minWidth: 18,
      height: 18,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 4,
      borderWidth: 2,
      borderColor: colors.background,
    },
    notifBadgeText: {
      fontFamily: Typography.fontFamily,
      color: '#FFFFFF',
      fontSize: 10,
      fontWeight: '800',
    },
    avatarCircle: {
      width: 44,
      height: 44,
      borderRadius: BorderRadius.md,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: colors.glassBorderHighlight,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.35,
      shadowRadius: 10,
      elevation: 6,
    },
    avatarText: {
      fontFamily: Typography.fontFamily,
      color: '#FFFFFF',
      fontSize: Typography.fontSize.lg,
      fontWeight: Typography.fontWeight.bold,
    },

    // 2x2 Summary Grid - Fixes gap issue with uniform spacing
    summaryGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      gap: 12,
      marginTop: Spacing.sm,
      marginBottom: Spacing.lg,
    },

    // Liquid Glass Card Styling
    glassCard: {
      backgroundColor: colors.glassCard,
      borderRadius: BorderRadius.xl,
      padding: Spacing.lg,
      borderWidth: 1,
      borderColor: colors.glassBorder,
      marginBottom: Spacing.lg,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.25,
      shadowRadius: 16,
      elevation: 6,
    },

    // Quick Expense Preview Widget
    expenseWidget: {
      backgroundColor: colors.glassCard,
      borderRadius: BorderRadius.xl,
      padding: Spacing.lg,
      borderWidth: 1,
      borderColor: colors.glassBorder,
      marginBottom: Spacing.lg,
      shadowColor: colors.accentEmerald,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.15,
      shadowRadius: 14,
      elevation: 5,
    },
    expenseWidgetHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: Spacing.sm,
    },
    expenseWidgetTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    expenseWidgetTitle: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.sm,
      fontWeight: Typography.fontWeight.semibold,
      color: colors.textSecondary,
    },
    expenseWidgetAmount: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xxl,
      fontWeight: Typography.fontWeight.heavy,
      color: colors.text,
      letterSpacing: -0.5,
      marginTop: 2,
    },
    expenseWidgetSubtext: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xs,
      color: colors.textMuted,
      marginTop: 4,
    },
    expenseViewBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: Spacing.sm,
      paddingVertical: Spacing.xs,
      borderRadius: BorderRadius.sm,
      backgroundColor: colors.surfaceHighlight,
    },
    expenseViewText: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xs,
      color: colors.primaryLight,
      fontWeight: Typography.fontWeight.semibold,
    },

    emptySchedule: {
      backgroundColor: colors.glassCard,
      borderRadius: BorderRadius.xl,
      padding: Spacing.xl,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.glassBorder,
      marginBottom: Spacing.md,
    },
    emptyScheduleIcon: {
      marginBottom: Spacing.sm,
    },
    emptyScheduleText: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.md,
      color: colors.text,
      fontWeight: Typography.fontWeight.semibold,
      textAlign: 'center',
    },
    emptyScheduleSub: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xs,
      color: colors.textMuted,
      marginTop: 4,
      textAlign: 'center',
    },
  });
