import { StyleSheet } from 'react-native';
import { ThemeColors, Typography, BorderRadius, Spacing } from '../../constants/theme';

export const createOnboardingStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      justifyContent: 'space-between',
      paddingHorizontal: Spacing.xl,
      paddingVertical: Spacing.xxl,
    },
    topSection: {
      alignItems: 'center',
      marginTop: Spacing.xl,
    },
    logoWrapper: {
      width: 88,
      height: 88,
      borderRadius: BorderRadius.xl,
      backgroundColor: colors.glassCard,
      borderWidth: 2,
      borderColor: colors.glassBorderHighlight,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: Spacing.lg,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.35,
      shadowRadius: 20,
      elevation: 10,
    },
    appTitle: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xxxl,
      fontWeight: Typography.fontWeight.heavy,
      color: colors.text,
      letterSpacing: -0.5,
    },
    tagline: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.sm,
      fontWeight: Typography.fontWeight.semibold,
      color: colors.primaryLight,
      marginTop: 4,
      letterSpacing: 0.5,
    },

    // Features Highlights Card
    featuresCard: {
      backgroundColor: colors.glassCard,
      borderRadius: BorderRadius.xl,
      padding: Spacing.lg,
      borderWidth: 1,
      borderColor: colors.glassBorder,
      gap: 14,
      marginVertical: Spacing.lg,
    },
    featureRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    featureIconBox: {
      width: 36,
      height: 36,
      borderRadius: BorderRadius.md,
      backgroundColor: colors.surfaceHighlight,
      alignItems: 'center',
      justifyContent: 'center',
    },
    featureText: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.sm,
      fontWeight: Typography.fontWeight.medium,
      color: colors.text,
      flex: 1,
    },

    // Form Section
    formSection: {
      backgroundColor: colors.glassCard,
      borderRadius: BorderRadius.xl,
      padding: Spacing.lg,
      borderWidth: 1,
      borderColor: colors.glassBorder,
    },
    inputLabel: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xs,
      fontWeight: Typography.fontWeight.bold,
      color: colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      marginBottom: Spacing.xs,
    },
    inputField: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.md,
      color: colors.text,
      backgroundColor: colors.surfaceHighlight,
      borderRadius: BorderRadius.md,
      paddingHorizontal: Spacing.md,
      height: 50,
      borderWidth: 1,
      borderColor: colors.borderLight,
      marginBottom: Spacing.md,
    },
    primaryBtn: {
      height: 52,
      borderRadius: BorderRadius.xl,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.35,
      shadowRadius: 16,
      elevation: 8,
    },
    primaryBtnText: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.md,
      fontWeight: Typography.fontWeight.heavy,
      color: '#FFFFFF',
      letterSpacing: 0.3,
    },
    footerNote: {
      fontFamily: Typography.fontFamily,
      fontSize: 11,
      color: colors.textMuted,
      textAlign: 'center',
      marginTop: Spacing.sm,
    },
  });
