import { StyleSheet } from 'react-native';
import { ThemeColors, Typography, BorderRadius, Spacing } from '../../constants/theme';

export const createExpensesStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
    },
    scrollContent: {
      paddingBottom: 100,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: Spacing.md,
      marginBottom: Spacing.xs,
    },
    headerTitle: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xxl,
      fontWeight: Typography.fontWeight.heavy,
      color: colors.text,
      letterSpacing: -0.4,
    },
    headerSubtitle: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xs,
      color: colors.textMuted,
      marginTop: 2,
    },

    // Month Selector Glass Bar
    monthSelector: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.glassCard,
      borderWidth: 1,
      borderColor: colors.glassBorder,
      borderRadius: BorderRadius.xl,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm + 2,
      marginBottom: Spacing.lg,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 10,
      elevation: 4,
    },
    monthNavBtn: {
      width: 38,
      height: 38,
      borderRadius: BorderRadius.md,
      backgroundColor: colors.surfaceHighlight,
      alignItems: 'center',
      justifyContent: 'center',
    },
    monthTitleContainer: {
      alignItems: 'center',
    },
    monthTitle: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.lg,
      fontWeight: Typography.fontWeight.bold,
      color: colors.text,
    },
    monthYearSub: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xs,
      color: colors.primaryLight,
      fontWeight: Typography.fontWeight.semibold,
      marginTop: 1,
    },

    // Big Total Spend Hero Glass Card
    heroCard: {
      backgroundColor: colors.glassCard,
      borderRadius: BorderRadius.xl,
      padding: Spacing.xl,
      borderWidth: 1,
      borderColor: colors.glassBorderHighlight,
      marginBottom: Spacing.lg,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.25,
      shadowRadius: 18,
      elevation: 8,
    },
    heroCardTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
    },
    heroLabel: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xs,
      fontWeight: Typography.fontWeight.semibold,
      color: colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
    },
    heroAmount: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.display,
      fontWeight: Typography.fontWeight.heavy,
      color: colors.text,
      letterSpacing: -1,
      marginTop: 4,
    },
    deltaBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: Spacing.sm,
      paddingVertical: 4,
      borderRadius: BorderRadius.full,
      backgroundColor: colors.surfaceHighlight,
    },
    deltaBadgePositive: {
      backgroundColor: colors.errorBg,
    },
    deltaBadgeNegative: {
      backgroundColor: colors.successBg,
    },
    deltaText: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xs,
      fontWeight: Typography.fontWeight.bold,
    },

    // 2-Column Metrics Row
    metricsRow: {
      flexDirection: 'row',
      gap: 12,
      marginBottom: Spacing.lg,
    },
    metricCard: {
      flex: 1,
      backgroundColor: colors.glassCard,
      borderRadius: BorderRadius.xl,
      padding: Spacing.md + 2,
      borderWidth: 1,
      borderColor: colors.glassBorder,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 3,
    },
    metricIconRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 6,
    },
    metricIconWrapper: {
      width: 32,
      height: 32,
      borderRadius: BorderRadius.sm,
      alignItems: 'center',
      justifyContent: 'center',
    },
    metricLabel: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xs,
      color: colors.textSecondary,
      fontWeight: Typography.fontWeight.medium,
    },
    metricValue: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.lg,
      fontWeight: Typography.fontWeight.bold,
      color: colors.text,
      marginTop: 2,
    },

    // Month-over-Month Comparison Chart Section
    chartCard: {
      backgroundColor: colors.glassCard,
      borderRadius: BorderRadius.xl,
      padding: Spacing.lg,
      borderWidth: 1,
      borderColor: colors.glassBorder,
      marginBottom: Spacing.lg,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.2,
      shadowRadius: 12,
      elevation: 4,
    },
    chartHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: Spacing.lg,
    },
    chartTitle: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.md,
      fontWeight: Typography.fontWeight.bold,
      color: colors.text,
    },
    chartLegend: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xs,
      color: colors.textMuted,
    },
    chartBarsContainer: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      justifyContent: 'space-between',
      height: 140,
      paddingTop: 10,
      paddingBottom: 2,
    },
    barColumn: {
      flex: 1,
      alignItems: 'center',
      height: '100%',
      justifyContent: 'flex-end',
    },
    barAmountTooltip: {
      fontFamily: Typography.fontFamily,
      fontSize: 9,
      fontWeight: '700',
      color: colors.textSecondary,
      marginBottom: 4,
    },
    barTrack: {
      width: 22,
      height: 100,
      backgroundColor: colors.surfaceHighlight,
      borderRadius: BorderRadius.sm,
      justifyContent: 'flex-end',
      overflow: 'hidden',
    },
    barFill: {
      width: '100%',
      backgroundColor: colors.primaryLight,
      borderRadius: BorderRadius.sm,
    },
    barFillCurrent: {
      backgroundColor: colors.accentPink,
      borderWidth: 1,
      borderColor: '#FFFFFF',
    },
    barLabel: {
      fontFamily: Typography.fontFamily,
      fontSize: 10,
      fontWeight: Typography.fontWeight.semibold,
      color: colors.textMuted,
      marginTop: 6,
    },
    barLabelCurrent: {
      color: colors.primaryLight,
      fontWeight: Typography.fontWeight.bold,
    },

    // Category Breakdown Section
    categorySection: {
      backgroundColor: colors.glassCard,
      borderRadius: BorderRadius.xl,
      padding: Spacing.lg,
      borderWidth: 1,
      borderColor: colors.glassBorder,
      marginBottom: Spacing.lg,
    },
    sectionTitle: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.md,
      fontWeight: Typography.fontWeight.bold,
      color: colors.text,
      marginBottom: Spacing.md,
    },
    categoryRow: {
      marginBottom: Spacing.md,
    },
    categoryInfoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 4,
    },
    categoryLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    categoryDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
    },
    categoryName: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.sm,
      fontWeight: Typography.fontWeight.semibold,
      color: colors.text,
    },
    categoryRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    categoryAmount: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.sm,
      fontWeight: Typography.fontWeight.bold,
      color: colors.text,
    },
    categoryPercent: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xs,
      color: colors.textMuted,
    },
    categoryProgressBar: {
      height: 6,
      backgroundColor: colors.surfaceHighlight,
      borderRadius: 3,
      overflow: 'hidden',
    },
    categoryProgressFill: {
      height: '100%',
      borderRadius: 3,
    },

    // Transactions List Section
    transactionItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.glassCard,
      borderRadius: BorderRadius.lg,
      padding: Spacing.md,
      borderWidth: 1,
      borderColor: colors.glassBorder,
      marginBottom: Spacing.sm,
    },
    transactionLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      flex: 1,
    },
    transactionIconBox: {
      width: 42,
      height: 42,
      borderRadius: BorderRadius.md,
      alignItems: 'center',
      justifyContent: 'center',
    },
    transactionDetails: {
      flex: 1,
    },
    transactionTitle: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.sm,
      fontWeight: Typography.fontWeight.bold,
      color: colors.text,
    },
    transactionMeta: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.xs,
      color: colors.textMuted,
      marginTop: 2,
    },
    transactionAmount: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.md,
      fontWeight: Typography.fontWeight.heavy,
      color: colors.text,
    },

    emptyContainer: {
      backgroundColor: colors.glassCard,
      borderRadius: BorderRadius.xl,
      padding: Spacing.xxxl,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.glassBorder,
      marginTop: Spacing.md,
    },
    emptyIcon: {
      marginBottom: Spacing.md,
    },
    emptyTitle: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.lg,
      fontWeight: Typography.fontWeight.bold,
      color: colors.text,
      textAlign: 'center',
    },
    emptySub: {
      fontFamily: Typography.fontFamily,
      fontSize: Typography.fontSize.sm,
      color: colors.textMuted,
      marginTop: 4,
      textAlign: 'center',
    },
  });
